name: Teste da Prova de Programação

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: biblioteca
          MYSQL_USER: admin
          MYSQL_PASSWORD: ifsp@1234
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uadmin -pifsp@1234"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Aguardar MySQL subir
        run: |
          echo "Esperando MySQL..."
          for i in {30..0}; do
            # ✅ CORRIGIDO: Agora usa admin consistentemente
            if mysqladmin ping -h"127.0.0.1" -uadmin -pifsp@1234 --silent; then
              echo "MySQL está rodando!"
              break
            fi
            echo "Aguardando MySQL... ($i segundos restantes)"
            sleep 2
          done

      - name: Criar esquema inicial
        run: |
          mysql -h 127.0.0.1 -uadmin -pifsp@1234 biblioteca < scripts/init.sql

      - name: Rodar testes
        run: npm test
        env:
          # ✅ CORRIGIDO: Indentação correta (2 espaços)
          DB_HOST: 127.0.0.1
          DB_USER: admin
          DB_PASSWORD: ifsp@1234
          DB_NAME: biblioteca

      - name: Rodar ESLint
        run: npx eslint src/**/*.js